services:

  mysql-usuario:
    image: mysql:8.0
    container_name: mysql-usuario
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: db_usuario_service
    ports:
      - "3307:3306"
    restart: always

  mysql-auth:
    image: mysql:8.0
    container_name: mysql-auth
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: db_auth_service
    ports:
      - "3308:3306"
    restart: always

  mysql-cancha:
    image: mysql:8.0
    container_name: mysql-cancha
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: db_cancha_service
    ports:
      - "3309:3306"
    restart: always

  mysql-reserva:
    image: mysql:8.0
    container_name: mysql-reserva
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: db_reserva_service
    ports:
      - "3310:3306"
    restart: always

  mysql-pago:
    image: mysql:8.0
    container_name: mysql-pago
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: db_pago_service
    ports:
      - "3311:3306"
    restart: always

  mysql-sede:
    image: mysql:8.0
    container_name: mysql-sede
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: db_sede_service
    ports:
      - "3312:3306"
    restart: always

  mysql-horario:
    image: mysql:8.0
    container_name: mysql-horario
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: db_horario_service
    ports:
      - "3313:3306"
    restart: always

  mysql-disponibilidad:
    image: mysql:8.0
    container_name: mysql-disponibilidad
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: db_disponibilidad_service
    ports:
      - "3314:3306"
    restart: always

  mysql-notificacion:
    image: mysql:8.0
    container_name: mysql-notificacion
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: db_notificacion_service
    ports:
      - "3315:3306"
    restart: always

  usuario-service:
    build: ./usuario-service
    container_name: usuario-service
    ports:
      - "7091:7091"
    depends_on:
      - mysql-usuario
    restart: always

  auth-service:
    build: ./auth-service
    container_name: auth-service
    ports:
      - "7101:7101"
    depends_on:
      - mysql-auth
    restart: always

  cancha-service:
    build: ./cancha-service
    container_name: cancha-service
    ports:
      - "7092:7092"
    depends_on:
      - mysql-cancha
    restart: always

  reserva-service:
    build: ./reserva-service
    container_name: reserva-service
    ports:
      - "7093:7093"
    depends_on:
      - mysql-reserva
    restart: always

  pago-service:
    build: ./pago-service
    container_name: pago-service
    ports:
      - "7094:7094"
    depends_on:
      - mysql-pago
    restart: always

  sede-service:
    build: ./sede-service
    container_name: sede-service
    ports:
      - "7095:7095"
    depends_on:
      - mysql-sede
    restart: always

  horario-service:
    build: ./horario-service
    container_name: horario-service
    ports:
      - "7096:7096"
    depends_on:
      - mysql-horario
    restart: always

  disponibilidad-service:
    build: ./disponibilidad-service
    container_name: disponibilidad-service
    ports:
      - "7097:7097"
    depends_on:
      - mysql-disponibilidad
    restart: always

  notificacion-service:
    build: ./notificacion-service
    container_name: notificacion-service
    ports:
      - "7098:7098"
    depends_on:
      - mysql-notificacion
    restart: always

  api-gateway:
    build: ./api-gateway
    container_name: api-gateway
    ports:
      - "7090:7090"
    depends_on:
      - usuario-service
      - auth-service
      - cancha-service
      - reserva-service
      - pago-service
      - sede-service
      - horario-service
      - disponibilidad-service
      - notificacion-service
    restart: always