server:
  port: 7091

spring:
  application:
    name: usuario-service

  datasource:
    url: jdbc:mysql://localhost:3306/db_usuario_service?createDatabaseIfNotExist=true
    username: root
    password:

  liquibase:
    enabled: true
    change-log: classpath:/db/changelog/db.changelog-master.yaml

  jpa:
    hibernate:
      ddl-auto: none
    show-sql: true

  security:
    oauth2:
      resourceserver:
        jwt:
          secret-key: esta_es_nuestra_klae_secreta_123456789_viva_el_ping_pong