server:
  port: 7094

spring:
  application:
    name: pago-service

  datasource:
    url: jdbc:mysql://localhost:3306/db_pago_service?createDatabaseIfNotExist=true&useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=UTC
    username: root
    password:

  liquibase:
    enabled: true
    change-log: classpath:/db/changelog/db.changelog-master.yaml

  jpa:
    hibernate:
      ddl-auto: none
    show-sql: true

springdoc:
  api-docs:
    enabled: true

  swagger-ui:
    enabled: true
    path: /doc/swagger-ui.html