server:
  port: 7096

spring:
  application:
    name: horario-service

  datasource:
    url: jdbc:mysql://localhost:3306/db_horario_service?createDatabaseIfNotExist=true
    username: root
    password:

  liquibase:
    change-log: classpath:db/changelog/db.changelog-master.yaml

  jpa:
    hibernate:
      ddl-auto: none