server:
  port: 7095

spring:
  application:
    name: sede-service

  datasource:
    url: jdbc:mysql://localhost:3306/db_sede_service?createDatabaseIfNotExist=true
    username: root
    password:

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true