server:
  port: 7099

spring:
  application:
    name: resena-service

  datasource:
    url: jdbc:mysql://localhost:3306/db_resena_service?createDatabaseIfNotExist=true
    username: root
    password:

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true