server:
  port: 7092

spring:
  application:
    name: cancha-service

  datasource:
    url: jdbc:mysql://localhost:3306/db_cancha_service?createDatabaseIfNotExist=true
    username: root
    password:

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true